# Generated by Django 5.2.4 on 2025-11-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("admin_app", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="MaskedCallSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("masked_number", models.CharField(db_index=True, max_length=32)),
                (
                    "caller_real_number",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "receiver_real_number",
                    models.CharField(db_index=True, max_length=32),
                ),
                ("qr_id", models.CharField(blank=True, default="", max_length=64)),
                ("reason", models.TextField(blank=True, default="")),
                ("call_sid", models.CharField(blank=True, default="", max_length=64)),
                ("status", models.CharField(default="initiated", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session_id"], name="admin_app_m_session_888460_idx"
                    ),
                    models.Index(
                        fields=["masked_number"], name="admin_app_m_masked__8dd5fa_idx"
                    ),
                    models.Index(
                        fields=["receiver_real_number"],
                        name="admin_app_m_receive_d33e1c_idx",
                    ),
                ],
            },
        )
    ]
