# Generated by Django 5.2.4 on 2025-11-18 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("admin_app", "0002_maskedcallsession")]

    operations = [migrations.DeleteModel(name="MaskedCallSession")]
