# Generated by Django 5.2.4 on 2026-05-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_delete_maskedcallsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRouteIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_key', models.CharField(db_index=True, max_length=10, unique=True)),
                ('destination', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
